spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USER}:${MONGO_PASS}@carsmongodb.global.mongocluster.cosmos.azure.com?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000
      database: carsdb
